services:
  app:
    container_name: blog-app
    build:
      context: .
      dockerfile: ./infra/node/Dockerfile
    user: node
    tty: true
    ports:
      - 127.0.0.1:3000:3000
    volumes:
      - .:/workspace:cached
    working_dir: /workspace
    environment:
      - NODE_ENV=development
    command: make dev
