name: Install Dependencies
description: Install project dependencies and optionally build the application

inputs:
  build:
    description: Whether to execute build
    required: false
    # Workaround: https://github.com/actions/runner/issues/2238
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
    - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
      with:
        bun-version-file: .bun-version
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: .node-version
    - run: bun install --frozen-lockfile
      shell: bash
    - if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
