name: Install Dependencies
description: Install project dependencies and optionally build the application

inputs:
  build:
    description: Whether to execute build
    required: false
    # Workaround: https://github.com/actions/runner/issues/2238
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: oven-sh/setup-bun@3d267786b128fe76c2f16a390aa2448b815359f3 # v2
      with:
        bun-version-file: .bun-version
    - uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version-file: .node-version
    - run: bun install --frozen-lockfile
      shell: bash
    - if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
