name: Install Dependencies
description: Install project dependencies and optionally build the application

inputs:
  build:
    description: Whether to execute build
    required: false
    # Workaround: https://github.com/actions/runner/issues/2238
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
    - uses: oven-sh/setup-bun@b7a1c7ccf290d58743029c4f6903da283811b979 # v2
      with:
        bun-version-file: .bun-version
    - uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
      with:
        node-version-file: .node-version
    - run: bun install --frozen-lockfile
      shell: bash
    - if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
