name: Install Dependencies
description: Install project dependencies and optionally build the application

inputs:
  build:
    description: Whether to execute build
    required: false
    # Workaround: https://github.com/actions/runner/issues/2238
    default: 'false'

runs:
  using: 'composite'
  steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
    - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2
      with:
        bun-version-file: .bun-version
    - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version-file: .node-version
    - name: Install Dependencies
      run: bun install --frozen-lockfile
      shell: bash
    - name: Build
      if: ${{ inputs.build == 'true' }}
      run: bun run build
      shell: bash
