name: Check links

on:
  push:
    branches:
      - main

jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Check Markdown links
        uses: lycheeverse/lychee-action@v2
        with:
          args: --verbose --no-progress './src/content/posts/*.md'
