name: Check links

on:
  push:
    branches:
      - develop
      - main


jobs:
  markdown-link-check:
    name: Check links
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Check Markdown links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-verbose-mode: 'yes'
          folder-path: './src/content/posts/'
