name: Dependencies

on:
  pull_request:
    types:
      - labeled

jobs:
  deps:
    name: Update dependencies
    if: github.event.label.name == 'deps[bot]'
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - name: Install Nix
        uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c # v26
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Dump toolchain updates
        run: nix develop .#deps --command node --version > .node-version
      - name: Commit files modified in devShell
        uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        with:
          commit_message: Apply toolchain updates
