name: Sync toolchain versions

on:
  pull_request:
    paths:
      - 'flake.lock'

jobs:
  toolchain:
    name: Sync toolchain versions
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4
      - name: Install Nix
        uses: cachix/install-nix-action@ba0dd844c9180cbf77aa72a116d6fbc515d0e87b # v27
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Put Node.js version
        run: nix run nixpkgs#nodejs-slim --inputs-from . -- --version > .node-version
      - name: Put Bun version
        run: |
          BUN_VERSION=$(nix run nixpkgs#bun --inputs-from . -- --version)
          nix run nixpkgs#dasel -- put -f wrangler.toml -v $BUN_VERSION '.vars.BUN_VERSION'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: Apply toolchain updates
