name: Sync Toolchain Versions

on:
  pull_request:
    paths:
      - '.github/workflows/sync-toolchain.yml'
      - 'flake.lock'

jobs:
  sync-toolchain-versions:
    name: Sync Toolchain Versions
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16
      - name: Setup Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: Get the Node.js version and update .node-version and renovate.json
        run: |
          NODE_VERSION=$(nix develop --command node --version)
          echo ${NODE_VERSION:1} > .node-version
          nix run nixpkgs#jq --inputs-from . -- \
            "walk(if type == \"object\" and has(\"allowedVersions\") then .allowedVersions = \"<=${NODE_VERSION:1}\" else . end)" \
            renovate.json > tmp.json
          mv tmp.json renovate.json
          BIOME_VERSION=$(nix eval .#meta.package.devDependencies."@biomejs/biome" --raw)
          nix develop --command bunx @biomejs/biome@$BIOME_VERSION check --write renovate.json
      - name: Get the Bun version and update .bun-version
        run: |
          BUN_VERSION=$(nix develop --command bun --version)
          echo $BUN_VERSION > .bun-version
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@e348103e9026cc0eee72ae06630dbe30c8bf7a79 # v5
        with:
          commit_message: 'chore(deps): Apply toolchain updates'
