name: Sync toolchain versions

on:
  pull_request:
    paths:
      - '.github/workflows/sync-toolchain.yml'
      - 'flake.lock'

jobs:
  toolchain:
    name: Sync
    runs-on: ubuntu-24.04
    timeout-minutes: 60
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install Nix
        uses: cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72 # v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Put Node.js version
        run: |
          NODE_VERSION=$(nix run nixpkgs#nodejs-slim --inputs-from . -- --version)
          echo $NODE_VERSION > .node-version
          nix run nixpkgs#dasel --inputs-from . -- put \
            --file renovate.json \
            --value ${NODE_VERSION:1} \
            'packageRules.all().property(matchPackageNames?).filter(equal(type(),array)).first().filter(equal(.,@types/node)).parent().parent().allowedVersions'
          nix run nixpkgs#bun --inputs-from . -- biome check --write renovate.json
      - name: Put Bun version
        run: |
          BUN_VERSION=$(nix run nixpkgs#bun --inputs-from . -- --version)
          nix run nixpkgs#dasel --inputs-from . -- put \
            --file wrangler.toml \
            --value $BUN_VERSION \
            'vars.BUN_VERSION'
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@8621497c8c39c72f3e2a999a26b4ca1b5058a842 # v5
        with:
          commit_message: Apply toolchain updates
